<a href="https://colab.research.google.com/github/tulashiprasad/pytorch/blob/main/01_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[2,2,2], [3, 3,3], [4, 4,4], [5, 5, 5]]])
TENSOR

tensor([[[2, 2, 2],
         [3, 3, 3],
         [4, 4, 4],
         [5, 5, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 3])

### Random Tensors

Random tensors are important because the way many nerual networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data
 `Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`


In [ ]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand( 3, 4)
random_tensor

tensor([[0.0947, 0.8164, 0.6371, 0.5678],
        [0.3922, 0.2654, 0.1092, 0.6037],
        [0.5459, 0.4629, 0.5584, 0.8802]])

In [ ]:
# Create a random tensor with similar shape to an image tensor

random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels(RGB)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Onesm

In [ ]:
# Create a tensor of all zeors
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating Range of tensor and tensors-like

In [ ]:
tensor= torch.arange(start=0, end=1000, step=100)

In [ ]:
# Creating tensor like
tensor_like = torch.zeros_like(input=tensor)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data Types
 **Note:** Tensor datatyupes is one of the 3 big errors you'll run into with pytorch & deep learning

 1. Tensors not right datatype
 2. Tensors not right shape
 3. Tensors not on the right device


In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (eg, float32, float16, float64)
                               device= None, # in which device the computation is going on (eg, cpu or cuda)
                               requires_grad=False # wheteter to track or not The gradience of tensor when it goes through certain numerical operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensor attributes
1. Tensors not right datatype -> to do get datatype from tensor, can sue `tensor.dtye`
2. Tensors not right shape -> to gety shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device -> got get device from a tensor, can use `tensor.device`

In [ ]:
# Find out details about some tensor
some_tensor = torch.rand(3, 4)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)
* Addition
* Substraction
* Multipllication (element-wise)
* Division
* Matrix multiplication (dot product)

In [ ]:
# Matrix multiplication
tensor1 = torch.rand(3, 4)
tensor2 = torch.rand(4, 3)
torch.matmul(tensor1, tensor2)
tensor1 @ tensor2 # alternative way @ -> stands for matmult

tensor([[1.2433, 1.1509, 1.5048],
        [1.3210, 1.2647, 1.6276],
        [0.7333, 0.4829, 0.7804]])

## Finding the min, max, mean, sum, etc (tensor aggrigation)

### Finding the positional min and max
* tensor.argmin() -> returns the position of the tensor with min value
* tensor.argmax() -> returns the position of the tensor with max valuem

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to defined shape
* View - reuturn a view of a input tensor of certain shape but keep the same memory as teh origional tensor
* Stacking - combine multiplte tensor on top of each other( vstack) or side by side(stack)
* Squeeze - removes all `1` dimensions froma a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions swapped in a certain way


In [ ]:
# Lets create a tensor

import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
import torch
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\n New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

 New shape: torch.Size([1, 9])


In [ ]:
 import torch

 # torch.permute() re arranges the dimensions of a target tensor in a specified order
 x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

 # Permute the original tensor to rearrange the axis (or dim) order
 x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2 and 2 -> 0

 print(f"Previous shape: {x_original.shape}")
 print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)
Indexing with pyTorch is similar to indexing with numpy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
print(f"The dimensions of the tensor are : {x.ndim}")

# to obtain [3, 6, 9]

x[:, :, 2]


The dimensions of the tensor are : 3


tensor([[3, 6, 9]])

In [ ]:
# to obtain 8
x[:, 2, 1 ]

tensor([8])

In [ ]:
tensor = torch.rand(1, 4, 4)
tensor

tensor([[[0.4928, 0.4730, 0.3191, 0.1409],
         [0.6062, 0.1018, 0.2802, 0.0845],
         [0.3383, 0.5907, 0.7306, 0.8911],
         [0.2912, 0.8216, 0.2133, 0.5802]]])

In [ ]:
tensor[:,:, 3]

tensor([[0.1409, 0.0845, 0.8911, 0.5802]])

In [ ]:
## Reproducbility ( trying to take random out of random)
import torch
# Lets's make some random but reproducable tensors

#Set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects in GPUs(and makeing faster computations)


In [ ]:
!nvidia-smi

Sat Jun  7 09:10:13 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# Check for GPU access with PyTorch

import torch
torch.cuda.is_available()

True

Follow the documentation for the best practice for device agnostic code: https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU
the reason behind this is faster computation

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not ton GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to numpy

# tensor_on_gpu.numpy()

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])